platform :ios, '7.1'

pod 'AFNetworking', '~> 2.0'
pod 'ActionSheetPicker-3.0', '~> 2.0.3'
pod 'TPKeyboardAvoiding', '~> 1.2.10'
pod 'SDCAlertView', '2.5.4'
pod 'SVProgressHUD'
pod 'SDWebImage', '~>3.7'
pod 'SHSPhoneComponent'
pod 'Google/CloudMessaging'
pod 'CRToast', '~> 0.0.7'
