 devices([
   "iPhone X",
   "iPhone 8",
   "iPhone 8 Plus",
   "iPhone SE"
])

languages([
  "pt-BR"
])

scheme "Caronae"
app_identifier "br.ufrj.caronae"

output_directory "./screenshots"

localize_simulator true
clear_previous_screenshots true
reinstall_app true

workspace "./Caronae.xcworkspace"
