# A list of devices you want to take the screenshots from
 devices([
   "iPhone X",
   "iPhone 8",
   "iPhone 8 Plus",
   "iPhone SE",
])

languages([
  ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# The name of the scheme which contains the UI Tests
scheme "Caronae"
app_identifier "br.ufrj.caronae"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

clear_previous_screenshots true
reinstall_app true

# Choose which project/workspace to use
workspace "./Caronae.xcworkspace"

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
